config/routes.rb
TaskManager::Application.routes.draw do
  devise_for :users

  resources :tasks, only: [:create, :update, :destroy]

  resources :projects, only: [:index, :create, :update, :destroy]

  root to: 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  has_many :tasks, :dependent => :destroy
  validates :name, presence: true
  validates_uniqueness_of :name, scope: [:user_id]
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :expires_on, :is_done, :name, :project_id, :rank
  belongs_to :project
  delegate :user_id, :to => :project
  before_create :set_defaults
  default_scope order('rank DESC')
  validates :name, presence: true
  validates_uniqueness_of :name, scope: [:project_id]

  def tasks_for_rank_change(direction = 0)
    curr_rank = rank || 0
    new_rank = curr_rank + direction
    max_rank = maximum_rank

    return 0 if direction == 0 || new_rank <=0 || (curr_rank + direction) > max_rank

    tasks_curr_rank = Task.where("project_id = ? and rank = ? and id <> ?", project_id, new_rank, id)
  end

  def expired?
    expires_on < Date.today && !is_done
  end

  protected
  def set_defaults
    self.rank = maximum_rank + 1
    self.expires_on = Date.today + 3.days
  end

  def maximum_rank
    Task.where(project_id: project.id).maximum(:rank) || 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  def index
    @projects = current_user.projects

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # POST /projects
  def create
    @project = Project.new(params[:project])
    @project.user_id = current_user.id

    respond_to do |format|
      if @project.save
        format.js
      else
        format.js { render "shared/failure", locals: { messages: @project.errors.full_messages } }
      end
    end
  end

  # PUT /projects/1
  def update
    @project = Project.find(params[:id])

    if @project.user_id == current_user.id
      respond_to do |format|
        if @project.update_attributes(params[:project])
          format.js
        else
          format.js { render "shared/failure", locals: { messages: @project.errors.full_messages } }
        end
      end
    else
      redirect_to root_url
    end
  end

  # DELETE /projects/1
  def destroy
    @project = Project.find(params[:id])
    @project.destroy if @project.user_id == current_user.id

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # POST /tasks
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.user_id == current_user.id && @task.save
        format.js
      else
        format.js { render "shared/failure", locals: { messages: @task.errors.full_messages } }
      end
    end
  end

  # PUT /tasks/1
  def update
    @task = Task.find(params[:id])
    if @task.user_id == current_user.id
      direction = params[:direction].to_i

      if direction != 0
        tasks_to_change = @task.tasks_for_rank_change(direction)
        if tasks_to_change.respond_to?(:each)
          @task.rank = @task.rank + direction
          tasks_to_change.each do |task|
            curr_task = Task.find(task.id)
            curr_task.rank = curr_task.rank - direction
            curr_task.save
          end
        end
      end

      respond_to do |format|
        if @task.update_attributes(params[:task])
          format.js
        else
          format.js { render "shared/failure", locals: { messages: @task.errors.full_messages } }
        end
      end
    else
      redirect_to root_url
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy if @task.user_id == current_user.id

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def task_class(task)
    if task.expired?
      ' expired'
    elsif task.is_done
      ' done'
    else
      ''
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://documentcloud.github.com/underscore/underscore-min.js"></script>
</head>
<body>
<div id="wrapper">
<%= render 'shared/notice', notice: notice if notice %>
<%= render 'shared/alert', alert: alert if alert %>
<% if current_user %>
  <div class="right">
    <%= link_to("Log out", destroy_user_session_path, :method => :delete, style: "font-size: 1.2em; color: #000;") %>
  </div>
<% end %>
  <h1>Task Manager</h1>
  <%= yield %>
</div>
</body>
</html>

app/views/projects/_project.html.erb
<div class="project" id="project_<%= project.id %>">
  <div class="project_name" style="height: 40px;">
    <h2><%= project.name %></h2>
    <div class="right">
      <ul class="icons ui-widget ui-helper-clearfix">
        <li class="ui-state-default ui-corner-all">
          <span class="ui-icon ui-icon-pencil" onclick="$('#project_<%= project.id %>').html(_.template($('#editProject').html(), {id: <%= project.id %>, name: '<%=j project.name %>'})); MainCSS.perform(); return false;"></span>
        </li>
        <li class="ui-state-default ui-corner-all">
          <%= link_to '<span class="ui-icon ui-icon-trash"></span>'.html_safe, project, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
        </li>
      </ul>
    </div>
  </div>

  <div class="task_add">
    <%= form_tag tasks_url, method: :post, remote: true do %>
      <%= hidden_field_tag "task[project_id]", project.id %>
      <%= text_field_tag "task[name]", "", id: "t#{project.id}" %>
      <%= submit_tag "Add Task", onclick: "if(/^\s*$/.test($('#t#{project.id}').val())) { return false; };".html_safe %>
    <% end %>
  </div>

  <div id="project_<%= project.id %>_tasks">
    <%= render project.tasks %>
  </div>
</div>

app/views/projects/create.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

$('#projects').append("<%=j render @project %>");
MainCSS.perform();
$('#new_project_name').val('');

app/views/projects/destroy.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

$("#project_<%= @project.id %>").hide();

app/views/projects/index.html.erb
<div id="projects">
  <%= render @projects %>
</div>

<br />

<%= form_for(Project.new, remote: true) do |f| %>
  <%= f.text_field :name, id: "new_project_name", size: nil %>
  <%= f.submit 'Create Project', onclick: "if(/^\s*$/.test($('#new_project_name').val())) { return false; };".html_safe %>
<% end %>

<%= render 'projects/js/edit' %>
<%= render 'tasks/js/edit' %>

app/views/projects/js/_edit.html.erb
<script type="text/html" id="editProject">
  <form action="/projects/<%%= id %>" method="post" data-remote="true">
    <input name="_method" type="hidden" value="put" />
    <input type="hidden" name="project[id]" value="<%%= id %>" />
    <input type="text" name="project[name]" value="<%%= name %>" id="project_name" />
    <input type="submit" value="Edit" onclick="if(/^\s*$/.test($('#project_name').val())) { return false; };" />
  </form>
</script>

app/views/projects/update.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

$('#project_<%= @project.id %>').html("<%=j render @project %>");
MainCSS.perform();

app/views/shared/_alert.html.erb
<div class="ui-widget" id="alert">
  <div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
    <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span>
    <%= alert %></p>
  </div>
</div>

app/views/shared/_notice.html.erb
<div class="ui-widget" id="notice">
  <div class="ui-state-highlight ui-corner-all" style="margin-top: 20px; padding: 0 .7em;">
    <p><span class="ui-icon ui-icon-info" style="float: left; margin-right: .3em;"></span>
    <%= notice %></p>
  </div>
</div>

app/views/shared/failure.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

$('#wrapper').prepend("<%=j render 'shared/alert', alert: messages.join('<br/>') %>");

app/views/tasks/_task.html.erb
<div class="task" id="task_<%= task.id %>">
  <div class="left" style="margin-top: 7px;">
    <%= form_for(task, remote: true) do |f| %>
      <%= f.check_box :is_done, onchange: "$(this).closest('form').trigger('submit');".html_safe %>
    <% end %>
  </div>
  <div class="task_name<%= task_class(task) %>"><%= task.name %></div>
  <div class="right">
    <ul class="icons ui-widget ui-helper-clearfix">
      <li class="ui-state-default ui-corner-all">
        <%= link_to '<span class="ui-icon ui-icon-arrow-1-n"></span>'.html_safe, task_path(task, direction: 1), method: :put, remote: true %>
      </li>
      <li class="ui-state-default ui-corner-all">
        <%= link_to '<span class="ui-icon ui-icon-arrow-1-s"></span>'.html_safe, task_path(task, direction: -1), method: :put, remote: true %>
      </li>
      <li class="ui-state-default ui-corner-all">
        <%= link_to '<span class="ui-icon ui-icon-pencil"></span>'.html_safe, '#', onclick: "$('#task_#{task.id}').addClass('task_edit').html(_.template($('#editTask').html(), {id: #{task.id}, name: '#{j task.name}', expires_on: '#{task.expires_on.strftime("%d-%m-%Y")}'})); $('#task_expires_on').datepicker({ dateFormat: 'dd-mm-yy' }); MainCSS.perform(); return false;".html_safe %>
      </li>
      <li class="ui-state-default ui-corner-all">
        <%= link_to '<span class="ui-icon ui-icon-trash"></span>'.html_safe, task, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, style: "text-decoration: none;" %>
      </li>
    </ul>
  </div>
</div>

app/views/tasks/create.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

$('#project_<%= @task.project_id %>_tasks').html("<%=j render @task.project.tasks %>");
$('#t<%= @task.project_id %>').val('');
$('#task_<%= @task.id %>').css({opacity: 0}).animate({opacity: 1}, 700);

app/views/tasks/destroy.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

$('#project_<%= @task.project_id %>_tasks').html("<%=j render @task.project.tasks %>");

app/views/tasks/js/_edit.html.erb
<script type="text/html" id="editTask">
  <form action="/tasks/<%%= id %>" method="post" data-remote="true">
    <input name="_method" type="hidden" value="put" />
    <input type="hidden" name="task[id]" value="<%%= id %>" />
    <input type="text" name="task[name]" value="<%%= name %>" id="task_name" />
    <input type="text" name="task[expires_on]" value="<%%= expires_on %>" id="task_expires_on" />
    <input type="submit" value="Edit" onclick="if(/^\s*$/.test($('#task_name').val())) { return false; };" />
  </form>
</script>

app/views/tasks/update.js.erb
if ($('#notice').length == 1) { $('#notice').hide(); }
if ($('#alert').length == 1) { $('#alert').hide(); }

<% if params[:direction] %>
  $('#project_<%= @task.project_id %>_tasks').html("<%=j render @task.project.tasks %>");
<% else %>
  $('#task_<%= @task.id %>').replaceWith("<%=j render @task %>");
<% end %>